---
# defaults file for linux_lab_provisioning

# ============================================================
# SSH
# ============================================================

ssh_pub_key: "{{ lookup('file', '/home/unixadm/.ssh/id_rsa.pub') }}"


# ============================================================
# NETWORK
# ============================================================

gateway: 192.168.122.1

dns_servers:
  - 192.168.122.1
  - 8.8.8.8


# ============================================================
# LIBVIRT STORAGE
# ============================================================

libvirt_image_dir: "/home/libvirt-images"

libvirt_template_dir: "{{ libvirt_image_dir }}/templates"
libvirt_iso_dir: "{{ libvirt_image_dir }}/iso"
libvirt_vm_dir: "{{ libvirt_image_dir }}/vms"
libvirt_work_dir: "{{ libvirt_image_dir }}/work"
libvirt_trash_dir: "{{ libvirt_image_dir }}/trash"


# ============================================================
# RHEL / KICKSTART
# ============================================================

rhel_iso: "{{ libvirt_iso_dir }}/rhel-9.8-x86_64-dvd.iso"


# ============================================================
# GOLD IMAGE
# ============================================================

gold_image: "{{ libvirt_template_dir }}/rhel9-gold.qcow2"


# ============================================================
# PROVISIONING
# ============================================================

install_method: "gold"
operation: "provision"
disk_gb: 100
