---
# defaults file for linux_lab_provisioning

# ============================================================
# SSH
# ============================================================

ssh_pub_key: "{{ lookup('file', '/home/unixadm/.ssh/id_rsa.pub') }}"


# ============================================================
# NETWORK
# ============================================================

gateway: 192.168.122.1

dns_servers:
  - 192.168.122.1
  - 8.8.8.8


# ============================================================
# RHEL / KICKSTART
# ============================================================

rhel_iso: "/home/libvirt-images/iso/rhel-9.8-x86_64-dvd.iso"


# ============================================================
# PROVISIONING
# ============================================================

install_method: "gold"
operation: "provision"
disk_gb: 100
